### ISSUE TITLE
http://dl.john-ky.io/maven/releases is often down

### ISSUE THREAD

**Issue by velotelo** [newhoggy/hashids-scala#15]
This "http://dl.john-ky.io/maven/releases" is often down, resulting in "Unresolved dependency" in my project.

**Comment by ymeymann** [comment]
Same here...

**Comment by dmrolfs** [comment]
same...  bintray is pretty easy to get set up

**Comment by newhoggy** [comment]
Thanks for reporting this.  I did some initial work to publish to sonatype a while back.  I'll look at finishing that off.

**Comment by newhoggy** [comment]
Some want to give this a whirl?

```
libraryDependencies += "org.picoworks" %% "pico-hashids"  % "4.4.141"
```

Please note the package has been changed to `org.pico.hashids` as well.

**Comment by newhoggy** [comment]
The Github repo will also be moving into the `pico-works` Github organisation:

https://github.com/pico-works/pico-hashids

**Comment by newhoggy** [comment]
Anyone had any success?

**Comment by velotelo** [comment]
Thanks for update! Tested briefly, seems to be much better, but I'll give it a proper test later this week.

**Comment by velotelo** [comment]
Could you please update the readme in pico-hashids?

**Comment by newhoggy** [comment]
Updated.  If it's good, I'll close this ticket.

**Comment by velotelo** [comment]
Thanks. Yup, time to close it now.
