### ISSUE TITLE
Non compatible output when alphabet has no O and no 0

### ISSUE THREAD

**Issue by newhoggy** [newhoggy/hashids-scala#2]
For details, see: https://github.com/jiecao-fm/hashids-java/issues/23

**Comment by newhoggy** [comment]
After refactoring out implementation, new unit tests show that the correct behaviour can be achieved by supplying the correct values for `HashidsImpl(salt, minHashLength, effectiveAlphabet, seps, guards)`.

These values can be obtained by addition tracing to the python implementation to print the internal state of the Python `Hashids` object, and is a suitable work-around until I figure out what the state is incorrectly initialised for the Scala `Hashids` object.

**Comment by sirotopr** [comment]
@newhoggy Thanks for the quick workaround!

It indeed works:

``` scala
import org.hashids.impl.HashidsImpl

object Test extends App {
  val hashids = HashidsImpl("MyCamelCaseSalt", 10, "97ZP3LE8W5QKD4XRY21BVNJ", "FUITHCSA", "G6M")
  println(hashids.encode(1145))
}
```

`9Q7MJ3LVGW`

Gives the correct output, the same as the reference JavaScript implementation:  jiecao-fm/hashids-java#23

For reference: I got the values by running the Python with pdb `python -m pdb hashids-test.py`. Inside it I run `next` until Hashids object got initialized and run pretty print to get the values `pp vars(hashids)`.

**Comment by newhoggy** [comment]
I have identified the bug.  I'm going to think on how I am going to fix it.  I don't want to change the behaviour silently for people who already use the code.

**Comment by newhoggy** [comment]
Please have a look at the `README` for how to upgrade to latest version with reference implementation compatibility fix.

**Comment by sirotopr** [comment]
Nice @newhoggy! Good call on how to deal with the compatibility issue.

Thanks for being so quick on this. Indeed working:

``` scala
import org.hashids._

object Test extends App {
  val hashids = Hashids.reference("MyCamelCaseSalt", 10, "ABCDEFGHIJKLMNPQRSTUVWXYZ123456789")
  println(hashids.encode(1145))
}
```

`9Q7MJ3LVGW`
